# Generated by Django 3.2.7 on 2021-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='Room',
            field=models.IntegerField(default=True),
        ),
    ]
