# Generated by Django 3.2.7 on 2021-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_resident_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='Room',
            field=models.IntegerField(default=True, help_text='Enter your room Number'),
        ),
    ]
