# Generated by Django 3.2.7 on 2021-10-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=60, unique=True, verbose_name='email'),
        ),
    ]
