# Generated by Django 3.2.6 on 2021-09-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Location',
        ),
    ]
