# Generated by Django 3.2.6 on 2021-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20210903_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(default='Udupi', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.CharField(default='Abc', max_length=20),
        ),
    ]
